---
version: "3"
services:
  bitpollo:
    image: bitraten/bitpollo
    container_name: bitpollo
    environment:
      - JWT_SECRET
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
